#!/bin/bash

domain=$1
subdomain=$2

function get_record_info {
    sub_domain=$1
    record_type=$(dig $sub_domain.$domain | awk '/IN\sA/ {print $4}')
    echo "The subdomain $sub_domain is a A record and points to $record_type"
}

if [ -z "$subdomain" ]; then
    get_record_info www
    get_record_info lb-01
    get_record_info web-01
    get_record_info web-02
else
    get_record_info $subdomain
fi
