#!/usr/bin/env bash

# This Bash script displays the time for 12 hours and 59 minutes.
# It displays the hours from 0 to 12 and the minutes from 1 to 59.

hour=0
minute=1

while [ $hour -lt 13 ]
do
    echo "Hour: $hour"

    while [ $minute -lt 60 ]
    do
        echo $minute
        ((minute++))
    done

    ((hour++))
    minute=1
done
